import 'dotenv/config';
import express from 'express'; import cors from 'cors'; import helmet from 'helmet'; import {createServer} from 'node:http'; import {Server} from 'socket.io'; import {z} from 'zod';
const app=express(); const http=createServer(app); const io=new Server(http,{cors:{origin:process.env.CORS_ORIGIN?.split(',')||'*'}});
app.use(helmet()); app.use(cors({origin:process.env.CORS_ORIGIN?.split(',')||true})); app.use(express.json({limit:'10mb'}));
const id=()=>Math.random().toString(36).slice(2,11);
type User={id:string;name:string;handle:string;bio:string;verified:boolean;followers:number;following:number;createdAt:string;avatarIndex:number};
type Seller=User&{storeName:string;location:string;rating:number;products:number};
type Product={id:string;name:string;price:number;category:string;sellerId:string;image:string;fulfillment:'local'|'international';eta?:string;stock:number;tags:string[]};
const now=()=>new Date().toISOString();
const users:User[]=[{id:'u1',name:'Nia Hair',handle:'@niahair',bio:'Hair, beauty and pieces selected with the girlies in mind.',verified:true,followers:8300,following:312,createdAt:now(),avatarIndex:0},{id:'u2',name:'Amara Beauty',handle:'@amarabeauty',bio:'Glow, fragrance and everyday beauty.',verified:true,followers:12400,following:501,createdAt:now(),avatarIndex:1},{id:'u3',name:'Nana Glow',handle:'@nanaglow',bio:'Soft glam, style and good finds.',verified:false,followers:2800,following:428,createdAt:now(),avatarIndex:2}];
const sellers:Seller[]=users.slice(0,2).map((u,i)=>({...u,storeName:i?'Amara Beauty':'Nia Hair Studio',location:'Accra, Ghana',rating:4.9,products:i?38:74}));
const products:Product[]=[
{id:'p1',name:'Silk press statement wig',price:480,category:'Hair',sellerId:'u1',image:'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=900&q=85',fulfillment:'local',stock:12,tags:['wig','silk press','natural']},
{id:'p2',name:'Rose oud perfume',price:320,category:'Fragrance',sellerId:'u2',image:'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=85',fulfillment:'local',stock:7,tags:['sweet','long lasting']},
{id:'p3',name:'Soft glam kit',price:260,category:'Beauty',sellerId:'u2',image:'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=900&q=85',fulfillment:'local',stock:21,tags:['makeup','glam']},
{id:'p4',name:'Satin co-ord set',price:410,category:'Fashion',sellerId:'u1',image:'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=900&q=85',fulfillment:'international',eta:'35–52 days',stock:40,tags:['satin','set','import']}
];
const orders:any[]=[]; const bids:any[]=[];
app.get('/health',(_,res)=>res.json({ok:true,service:'herlo-api',time:now()}));
app.get('/api/home',(_,res)=>res.json({users,sellers,products,hero:{title:'Your next look is waiting.',subtitle:'Discover women-led shops, real recommendations and new drops.'}}));
app.get('/api/products',(req,res)=>{const q=String(req.query.q||'').toLowerCase();const category=String(req.query.category||'').toLowerCase();let out=products.filter(p=>(!q||[p.name,p.category,...p.tags].join(' ').toLowerCase().includes(q))&&(!category||p.category.toLowerCase()===category));res.json({products:out,total:out.length});});
app.get('/api/products/:id',(req,res)=>{const p=products.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({error:'Product not found'});res.json({product:p,seller:sellers.find(s=>s.id===p.sellerId)});});
app.get('/api/sellers',(req,res)=>{const q=String(req.query.q||'').toLowerCase();res.json({sellers:sellers.filter(s=>!q||s.name.toLowerCase().includes(q)||s.storeName.toLowerCase().includes(q))});});
app.get('/api/sellers/:id',(req,res)=>{const s=sellers.find(x=>x.id===req.params.id);if(!s)return res.status(404).json({error:'Seller not found'});res.json({seller:s,products:products.filter(p=>p.sellerId===s.id)});});
app.get('/api/feed',(_,res)=>res.json({posts:[{id:'post1',user:users[2],text:'Girls, help me choose 😭 Which one would you wear to a garden wedding?',image:'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=900&q=85',likes:284,comments:48,shares:16,createdAt:now()},{id:'post2',user:users[0],text:'New drop is live. Which texture should we bring back?',image:'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=85',likes:182,comments:31,shares:8,createdAt:now()}]}));
app.post('/api/posts', (req,res)=>{const body=z.object({userId:z.string(),text:z.string().min(1).max(5000),image:z.string().url().optional(),video:z.string().url().optional(),productId:z.string().optional(),visibility:z.enum(['public','followers','private']).default('public')}).parse(req.body);res.status(201).json({post:{id:id(),...body,likes:0,comments:0,shares:0,createdAt:now()}})});
app.post('/api/ai/chat',(req,res)=>{const body=z.object({message:z.string().min(1),userId:z.string().optional(),context:z.any().optional()}).parse(req.body);const matches=products.filter(p=>[p.name,p.category,...p.tags].join(' ').toLowerCase().includes(body.message.toLowerCase().split(/\s+/).find(w=>w.length>3)||'__none__')).slice(0,4);res.json({assistant:{name:'Lumi',reply:matches.length?`I found ${matches.length} close matches. I can compare their sellers, price, availability and delivery for you.`:`I’m listening. Tell me your budget, style, occasion or what you want to improve and I’ll search the marketplace.`,products:matches}})});
app.post('/api/orders/quote',(req,res)=>{const body=z.object({sellerLat:z.number(),sellerLng:z.number(),buyerLat:z.number(),buyerLng:z.number(),productId:z.string().optional()}).parse(req.body);res.json({provider:'yango',status:'provider_required',liveQuote:null,request:{...body},message:'Configure YANGO_API_URL and YANGO_API_KEY on the server to request a live quote.'})});
app.post('/api/orders',(req,res)=>{const body=z.object({buyerId:z.string(),productId:z.string(),quantity:z.number().int().min(1).default(1),address:z.object({label:z.string(),lat:z.number(),lng:z.number(),details:z.string().optional()})}).parse(req.body);const p=products.find(x=>x.id===body.productId);if(!p)return res.status(404).json({error:'Product not found'});if(p.stock<body.quantity)return res.status(409).json({error:'Insufficient stock'});const order={id:id(),...body,sellerId:p.sellerId,subtotal:p.price*body.quantity,status:'awaiting_payment',createdAt:now()};orders.push(order);res.status(201).json({order});});
app.get('/api/orders/:buyerId',(req,res)=>res.json({orders:orders.filter(o=>o.buyerId===req.params.buyerId)}));
app.post('/api/auctions/:productId/bids',(req,res)=>{const body=z.object({userId:z.string(),amount:z.number().positive()}).parse(req.body);const p=products.find(x=>x.id===req.params.productId);if(!p)return res.status(404).json({error:'Product not found'});const previous=bids.filter(b=>b.productId===p.id).sort((a,b)=>b.amount-a.amount)[0];if(previous&&body.amount<previous.amount+10)return res.status(400).json({error:'Bid must increase by at least GH₵10'});const bid={id:id(),productId:p.id,...body,createdAt:now()};bids.push(bid);io.emit('auction:bid',bid);res.status(201).json({bid});});
app.get('/api/notifications/:userId',(_,res)=>res.json({notifications:[{id:'n1',type:'like',text:'Nana Glow liked your post',read:false,createdAt:now()},{id:'n2',type:'order',text:'Your rider has been assigned',read:false,createdAt:now()}]}));
io.on('connection',socket=>{socket.on('join',room=>socket.join(String(room)));socket.on('typing',(data)=>socket.to(String(data.room)).emit('typing',data));socket.on('message',(data)=>io.to(String(data.room)).emit('message',{...data,createdAt:now()}));socket.on('call:invite',(data)=>io.to(String(data.userId)).emit('call:invite',data));});
const port=Number(process.env.PORT||4100);http.listen(port,()=>console.log(`Herlo API listening on ${port}`));
