import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { C } from '../constants/theme';
import { I } from '../components/Icons';
import { api } from '../lib/api';
import { getCurrentUser } from '../lib/auth';

type Product = { id: string; name: string; price: number; image?: string; sellerName?: string };
type AuctionState = { currentBid?: number; minimumIncrement?: number; status?: string };
export default function Auction() {
  const router = useRouter(); const { id, productId } = useLocalSearchParams<{ id?: string; productId?: string }>(); const selectedId = String(productId || id || '');
  const [product, setProduct] = useState<Product | null>(null); const [currentBid, setCurrentBid] = useState(0); const [minimumIncrement, setMinimumIncrement] = useState(10); const [submitting, setSubmitting] = useState(false); const [confirmation, setConfirmation] = useState(''); const [error, setError] = useState('');
  useEffect(() => { if (!selectedId) { setError('This auction is missing its product.'); return; } Promise.all([api<{ product: Product }>('/api/products/' + encodeURIComponent(selectedId)), api<AuctionState>('/api/auctions/' + encodeURIComponent(selectedId))]).then(([productResult, auction]) => { setProduct(productResult.product); setCurrentBid(Number(auction.currentBid || productResult.product.price || 0)); setMinimumIncrement(Number(auction.minimumIncrement || 10)); }).catch(err => setError(err instanceof Error ? err.message : 'Auction could not be loaded.')); }, [selectedId]);
  const nextBid = currentBid + minimumIncrement;
  async function placeBid() { if (!selectedId || !product) return; setSubmitting(true); setError(''); setConfirmation(''); try { const user = await getCurrentUser(); if (!user) throw new Error('Sign in before placing a bid.'); const response = await api<{ bid: { amount: number } }>('/api/auctions/' + encodeURIComponent(selectedId) + '/bids', { method: 'POST', body: JSON.stringify({ userId: user.id, amount: nextBid }) }); setCurrentBid(Number(response.bid.amount)); setConfirmation('Bid accepted. The auction result will be determined by the server.'); } catch (err) { setError(err instanceof Error ? err.message : 'Your bid could not be placed.'); } finally { setSubmitting(false); } }
  if (error && !product) return <SafeAreaView style={styles.safe}><View style={styles.center}><Text style={styles.title}>Auction unavailable</Text><Text style={styles.muted}>{error}</Text><Pressable onPress={() => router.back()} style={styles.btn}><Text style={styles.btnText}>Go back</Text></Pressable></View></SafeAreaView>;
  if (!product) return <SafeAreaView style={styles.safe}><View style={styles.center}><ActivityIndicator color={C.pink} /><Text style={styles.muted}>Loading auction…</Text></View></SafeAreaView>;
  return <SafeAreaView style={styles.safe}><View style={styles.top}><Pressable onPress={() => router.back()}><I name="back" size={34} /></Pressable><Text style={styles.heading}>Live auction</Text><I name="more" /></View><View style={styles.art}><Text style={{ fontSize: 85 }}>👗</Text><View style={styles.live}><Text style={styles.liveText}>LIVE</Text></View></View><View style={styles.body}><Text style={styles.kicker}>{product.sellerName || 'GIRLIES SELLER'} · VERIFIED</Text><Text style={styles.title}>{product.name}</Text><Text style={styles.label}>CURRENT BID</Text><Text style={styles.price}>GH₵ {currentBid.toFixed(0)}</Text><Text style={styles.meta}>Server-validated bids · Minimum increment GH₵ {minimumIncrement}</Text><View style={styles.bidRow}><View style={styles.current}><Text style={{ fontWeight: '900' }}>GH₵ {nextBid.toFixed(0)}</Text></View><Pressable onPress={placeBid} disabled={submitting} style={[styles.btn, submitting && { opacity: 0.55 }]}>{submitting ? <ActivityIndicator color="#FFF" /> : <Text style={styles.btnText}>Place bid</Text>}</Pressable></View>{confirmation ? <View style={styles.confirm}><Text style={styles.confirmTitle}>Bid submitted</Text><Text style={styles.confirmText}>{confirmation}</Text></View> : null}{error ? <View style={styles.error}><Text style={styles.errorText}>{error}</Text></View> : null}<Text style={styles.note}>If you win, you’ll confirm your delivery address before payment.</Text></View></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: C.bg }, center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 }, top: { height: 70, paddingHorizontal: 18, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, heading: { fontSize: 20, fontWeight: '900' }, art: { height: 300, margin: 18, borderRadius: 34, backgroundColor: C.lilac, alignItems: 'center', justifyContent: 'center', position: 'relative' }, live: { position: 'absolute', top: 15, right: 15, backgroundColor: C.coral, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 14 }, liveText: { fontSize: 9, fontWeight: '900' }, body: { padding: 20 }, kicker: { fontSize: 9, fontWeight: '900', letterSpacing: 1.2, color: C.muted }, title: { fontSize: 27, fontWeight: '900', marginTop: 6, textAlign: 'center' }, label: { fontSize: 9, fontWeight: '900', color: C.muted, letterSpacing: 1.2, marginTop: 20, textAlign: 'center' }, price: { fontSize: 25, fontWeight: '900', marginTop: 5, textAlign: 'center' }, meta: { textAlign: 'center', color: C.muted, fontSize: 11, marginTop: 6 }, bidRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 20 }, current: { flex: 1, height: 52, borderRadius: 26, backgroundColor: '#FFF', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: C.line }, btn: { minHeight: 52, paddingHorizontal: 20, borderRadius: 26, backgroundColor: C.ink, alignItems: 'center', justifyContent: 'center', marginTop: 14 }, btnText: { color: '#FFF', fontWeight: '900' }, confirm: { padding: 14, borderRadius: 17, backgroundColor: C.mint, marginTop: 14 }, confirmTitle: { fontWeight: '900' }, confirmText: { color: C.muted, fontSize: 11, lineHeight: 16, marginTop: 4 }, error: { padding: 14, borderRadius: 17, backgroundColor: C.rose, marginTop: 14 }, errorText: { color: C.plum, fontSize: 11 }, note: { color: C.muted, fontSize: 11, lineHeight: 16, marginTop: 16, textAlign: 'center' }, muted: { color: C.muted, fontSize: 12, lineHeight: 18, textAlign: 'center', marginTop: 8 } });
