import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { C } from '../constants/theme';
import { I } from '../components/Icons';
import { api } from '../lib/api';
import { getCurrentUser } from '../lib/auth';

type Product = { id: string; name: string; price: number; image?: string; sellerName?: string; stock?: number };
type AuctionState = { currentBid?: number; minimumIncrement?: number; status?: string };
const fallbackProduct: Product = { id: 'p1', name: 'Silk press statement wig', price: 480, sellerName: 'Nia Hair', stock: 12 };
export default function Auction() {
  const router = useRouter(); const params = useLocalSearchParams<{ id?: string; productId?: string }>(); const selectedId = String(params.productId || params.id || 'p1');
  const [product, setProduct] = useState<Product | null>(null); const [currentBid, setCurrentBid] = useState(fallbackProduct.price); const [minimumIncrement, setMinimumIncrement] = useState(10); const [status, setStatus] = useState('live'); const [loading, setLoading] = useState(true); const [serviceUnavailable, setServiceUnavailable] = useState(false); const [submitting, setSubmitting] = useState(false); const [message, setMessage] = useState('');
  const load = useCallback(async () => { setLoading(true); setMessage(''); setServiceUnavailable(false); const fallback = { ...fallbackProduct, id: selectedId }; try { const response = await api<{ product: Product }>('/api/products/' + encodeURIComponent(selectedId)); setProduct(response.product); setCurrentBid(Number(response.product.price || fallback.price)); } catch { setProduct(fallback); setCurrentBid(fallback.price); setServiceUnavailable(true); setMessage('The auction service is unavailable. The screen is still available; retry before bidding.'); } try { const auction = await api<AuctionState>('/api/auctions/' + encodeURIComponent(selectedId)); setCurrentBid(Number(auction.currentBid || fallback.price)); setMinimumIncrement(Number(auction.minimumIncrement || 10)); setStatus(auction.status || 'live'); } catch { setServiceUnavailable(true); } setLoading(false); }, [selectedId]);
  useEffect(() => { load(); }, [load]);
  async function placeBid() { if (!product) return; setSubmitting(true); setMessage(''); try { const user = await getCurrentUser(); if (!user) throw new Error('Sign in before placing a bid.'); const nextBid = currentBid + minimumIncrement; const response = await api<{ bid: { amount: number } }>('/api/auctions/' + encodeURIComponent(selectedId) + '/bids', { method: 'POST', body: JSON.stringify({ userId: user.id, amount: nextBid }) }); setCurrentBid(Number(response.bid.amount)); setServiceUnavailable(false); setMessage('Bid accepted by the server. The auction result will be determined server-side.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Your bid could not be placed.'); } finally { setSubmitting(false); } }
  if (loading) return <SafeAreaView style={styles.safe}><View style={styles.center}><ActivityIndicator color={C.pink} /><Text style={styles.muted}>Loading auction…</Text></View></SafeAreaView>;
  const shownProduct = product || { ...fallbackProduct, id: selectedId };
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.scroll}><View style={styles.top}><Pressable onPress={() => router.back()}><I name="back" size={34} /></Pressable><Text style={styles.heading}>Live auction</Text><View style={{ width: 34 }} /></View><View style={styles.art}><Text style={{ fontSize: 82 }}>👗</Text><View style={styles.live}><Text style={styles.liveText}>{status.toUpperCase()}</Text></View></View><View style={styles.card}><Text style={styles.kicker}>{shownProduct.sellerName || 'GIRLIES SELLER'} · VERIFIED</Text><Text style={styles.title}>{shownProduct.name}</Text>{serviceUnavailable ? <View style={styles.warning}><Text style={styles.warningTitle}>Auction connection unavailable</Text><Text style={styles.muted}>Live bids require the app backend. No local winner or fake bid is recorded.</Text><Pressable onPress={load} style={styles.retry}><Text style={styles.retryText}>Retry connection</Text></Pressable></View> : null}<Text style={styles.label}>CURRENT BID</Text><Text style={styles.price}>GH₵ {currentBid.toFixed(0)}</Text><Text style={styles.muted}>Minimum next bid: GH₵ {minimumIncrement.toFixed(0)}</Text>{message && !serviceUnavailable ? <View style={styles.confirm}><Text style={styles.confirmText}>{message}</Text></View> : null}<Pressable disabled={submitting} onPress={placeBid} style={[styles.bid, submitting && { opacity: 0.5 }]}>{submitting ? <ActivityIndicator color="#FFF" /> : <Text style={styles.bidText}>Place bid · GH₵ {(currentBid + minimumIncrement).toFixed(0)}</Text>}</Pressable></View></ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: C.bg }, scroll: { padding: 18, paddingBottom: 30 }, top: { height: 55, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, heading: { fontSize: 20, fontWeight: '900' }, center: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 10 }, art: { height: 220, borderRadius: 30, backgroundColor: C.plum, alignItems: 'center', justifyContent: 'center' }, live: { marginTop: 10, backgroundColor: C.coral, paddingHorizontal: 12, paddingVertical: 7, borderRadius: 16 }, liveText: { color: '#FFF', fontSize: 10, fontWeight: '900' }, card: { marginTop: -18, borderRadius: 30, backgroundColor: '#FFF', padding: 20, borderWidth: 1, borderColor: C.line }, kicker: { fontSize: 9, fontWeight: '900', letterSpacing: 1.2, color: C.muted }, title: { fontSize: 25, fontWeight: '900', marginTop: 8 }, label: { fontSize: 10, fontWeight: '900', color: C.muted, letterSpacing: 1.1, marginTop: 24 }, price: { fontSize: 34, fontWeight: '900', marginTop: 5 }, muted: { fontSize: 11, color: C.muted, marginTop: 5, lineHeight: 16 }, warning: { marginTop: 18, padding: 14, borderRadius: 18, backgroundColor: C.rose }, warningTitle: { fontWeight: '900' }, retry: { height: 42, borderRadius: 21, borderWidth: 1, borderColor: C.pink, alignItems: 'center', justifyContent: 'center', marginTop: 12 }, retryText: { color: C.pink, fontWeight: '900' }, confirm: { marginTop: 16, padding: 13, borderRadius: 17, backgroundColor: C.mint }, confirmText: { fontSize: 11, fontWeight: '800', lineHeight: 16 }, bid: { height: 54, borderRadius: 27, backgroundColor: C.ink, alignItems: 'center', justifyContent: 'center', marginTop: 20 }, bidText: { color: '#FFF', fontWeight: '900', fontSize: 15 } });
