import React,{useEffect,useState}from'react';
import{ActivityIndicator,Image,Pressable,ScrollView,StyleSheet,Text,View,Alert}from'react-native';
import{SafeAreaView}from'react-native-safe-area-context';
import{useLocalSearchParams,useRouter}from'expo-router';
import{C}from'../constants/theme';
import{I}from'../components/Icons';
import{Avatar,VerifiedMark}from'../Avatar';
import{LikeButton}from'../components/LikeButton';
import{getProductLikeState,setProductLike,getSessionUser,setFollow,normalizeImageUrls,recordSellerEvent}from'../lib/social';
import{supabase}from'../lib/supabase';
import { useCart } from '../lib/cart';

type Product={id:string;name:string;description?:string;category?:string;price:number;currency?:string;stock?:number;fulfillment?:string;estimated_arrival?:string;image_urls?:string[];attributes?:any;store_id:string};
type Seller={id:string;name:string;handle?:string;avatar_url?:string|null;rating?:number;location?:string;verified?:boolean};
function normalizeId(value:string|string[]|undefined){const raw=Array.isArray(value)?value[0]:value;if(!raw)return '';return raw;}
export default function Product(){
 const router=useRouter();const{id}=useLocalSearchParams<{id?:string}>();const productId=normalizeId(id);
  const[product,setProduct]=useState<Product|null>(null);const[seller,setSeller]=useState<Seller|null>(null);const[saved,setSaved]=useState(false);const[following,setFollowing]=useState(false);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
  const { addItem } = useCart();
 useEffect(()=>{let mounted=true;(async()=>{if(!productId){if(mounted){setError('Product could not be loaded.');setLoading(false);}return;}try{
   setLoading(true);setProduct(null);setSeller(null);setError('');
    const{data:p,error:pError}=await supabase.from('products').select('id,name,description,category,price,currency,stock,fulfillment,estimated_arrival,image_urls,attributes,store_id').eq('id',productId).maybeSingle();
   if(pError)throw pError;if(!p){setError('This listing is no longer available.');return;}if(!mounted)return;setProduct(p as Product);void recordSellerEvent({ storeId: p.store_id, productId: p.id, eventType: 'view', source: 'Shop' });
   const{data:store,error:storeError}=await supabase.from('stores').select('owner_id,name,rating,lat,lng,verification_status').eq('id',p.store_id).maybeSingle();
   if(storeError)throw storeError;
   if(store){const{data:profile,error:profileError}=await supabase.from('profiles').select('id,display_name,handle,avatar_url,verified,country,area,location').eq('id',store.owner_id).maybeSingle();if(profileError)throw profileError;
     if(mounted)setSeller({id:store.owner_id,name:profile?.display_name||store.name,handle:profile?.handle,avatar_url:profile?.avatar_url,rating:store.rating,location:[profile?.area&&profile?.location?`${profile.area} - ${profile.location}`:profile?.area||profile?.location,profile?.country].filter(Boolean).join(', '),verified:Boolean(profile?.verified)||store.verification_status==='verified'});
   }
   const me=await getSessionUser();if(me&&mounted){const liked=await getProductLikeState(p.id);setSaved(liked);if(store){const{data:f}=await supabase.from('follows').select('following_id').eq('follower_id',me.id).eq('following_id',store.owner_id).maybeSingle();setFollowing(Boolean(f));}}
 }catch(e:any){if(mounted)setError(e?.message||'Product could not be loaded.');}finally{if(mounted)setLoading(false);}})();return()=>{mounted=false;};},[productId]);
 const toggleSaved=async()=>{if(!product)return;const next=!saved;setSaved(next);try{const verified=await setProductLike(product.id,next);setSaved(verified);}catch(e:any){setSaved(!next);Alert.alert('Save failed',e?.message||'Could not save this product.');}};
 const toggleFollow=async()=>{if(!seller)return;const next=!following;setFollowing(next);try{const verified=await setFollow(seller.id,next);setFollowing(verified);}catch(e:any){setFollowing(!next);Alert.alert('Follow failed',e?.message||'Could not save your follow.');}};
 if(!product)return <SafeAreaView style={s.safe}><View style={s.center}><Text style={s.title}>Product unavailable</Text><Text style={s.muted}>{error||'This listing is no longer available.'}</Text><Pressable onPress={()=>router.back()} style={s.buy}><Text style={s.buyText}>Go back</Text></Pressable></View></SafeAreaView>;
  const price=Number(product.price||0);const isInternational=product.fulfillment==='international';const sellerName=seller?.name||'Girlies seller';const image=product.image_urls?.[0];
  const addToCart=()=>{ void recordSellerEvent({ storeId: product.store_id, productId: product.id, eventType: 'cart', source: 'Shop' }); void addItem({id:product.id,name:product.name,price,image,seller:sellerName}); };
   return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.scroll}><View style={s.top}><Pressable onPress={()=>router.back()} style={s.round}><I name="back" size={30}/></Pressable><View style={s.actions}><Pressable style={s.round} onPress={()=>router.push('/cart')}><I name="cart" size={20} filled /></Pressable><Pressable style={s.round}><LikeButton liked={saved} onPress={toggleSaved} size={21}/></Pressable><Pressable style={s.round}><I name="share" size={20}/></Pressable></View></View>{image?<Image source={{uri:image}} style={s.gallery}/>:<View style={s.gallery}/>}<View style={s.info}><View style={s.tags}><Text style={s.tag}>{isInternational?'INTERNATIONAL':'LOCAL'}</Text><Text style={s.tag}>TOP RATED</Text></View><Text style={s.title}>{product.name}</Text><Text style={s.price}>GH₵ {price.toFixed(0)}</Text><View style={s.seller}><Avatar size={45} uri={seller?.avatar_url||undefined}/><View style={{flex:1}}><Text style={s.sellerName}>{sellerName} {seller?.verified&&<VerifiedMark size={16}/>}</Text><Text style={s.handle}>@{seller?.handle||'seller'}</Text><Text style={s.muted}>{seller?.rating? seller.rating+' · ':''}{seller?.location||'Location not added'}</Text></View><Pressable style={s.follow} onPress={toggleFollow}><Text style={s.followText}>{following?'Following':'Follow'}</Text></Pressable></View><Text style={s.heading}>Why girls like it</Text><Text style={s.body}>{product.description||'Product details, seller history and verified customer reviews appear here. Availability is checked before an order is created.'}</Text><View style={s.delivery}><I name="location" size={22} color={C.pink}/><View style={{flex:1}}><Text style={s.deliveryTitle}>Delivery calculated at checkout</Text><Text style={s.muted}>{isInternational?(product.estimated_arrival||'Estimated arrival shown before payment.'):'Add your address and we’ll request a live delivery quote.'}</Text></View></View><Pressable onPress={addToCart} style={s.addToCart}><I name="cart" size={19} color={C.ink} filled /><Text style={s.addToCartText}>Add to bag</Text><Text style={s.addToCartPrice}>GH₵ {price.toFixed(0)}</Text></Pressable><Pressable onPress={()=>router.push({pathname:'/checkout',params:{productId:product.id}})} style={s.buy}><Text style={s.buyText}>Buy now · GH₵ {price.toFixed(0)}</Text></Pressable><Pressable onPress={()=>router.push({pathname:'/auction',params:{productId:product.id}})} style={s.bid}><Text style={s.bidText}>Place a bid</Text></Pressable><View style={s.ask}><Text style={s.heading}>Ask the girls</Text><Text style={s.body}>“Does it look better in person?” · 24 replies</Text><Pressable onPress={()=>router.push('/community')}><Text style={s.link}>Join the conversation →</Text></Pressable></View></View></ScrollView></SafeAreaView>;
}
  const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},scroll:{paddingBottom:30},center:{flex:1,alignItems:'center',justifyContent:'center',padding:24},top:{padding:15,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},actions:{flexDirection:'row',gap:8},round:{width:43,height:43,borderRadius:22,backgroundColor:'#FFF',alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:C.line},gallery:{width:'100%',height:390,resizeMode:'cover',backgroundColor:C.rose},info:{padding:20},tags:{flexDirection:'row',gap:8},tag:{fontSize:9,fontWeight:'900',color:C.plum,backgroundColor:C.rose,paddingHorizontal:9,paddingVertical:6,borderRadius:12},title:{fontSize:26,fontWeight:'900',marginTop:10,color:C.ink,textAlign:'center'},price:{fontSize:20,fontWeight:'900',marginTop:7,textAlign:'center'},seller:{marginTop:20,padding:13,borderRadius:24,backgroundColor:'#FFF',flexDirection:'row',alignItems:'center',gap:10},sellerName:{fontWeight:'900',fontSize:13},handle:{fontSize:11,color:C.muted,marginTop:2},muted:{fontSize:11,color:C.muted,marginTop:4,textAlign:'center'},follow:{paddingHorizontal:12,paddingVertical:8,borderRadius:15,backgroundColor:C.cream},followText:{fontWeight:'900',fontSize:11},heading:{fontSize:17,fontWeight:'900',marginTop:23,marginBottom:7},body:{color:C.muted,fontSize:12,lineHeight:18},delivery:{marginTop:20,padding:15,borderRadius:24,backgroundColor:C.mint,flexDirection:'row',alignItems:'center',gap:10},deliveryTitle:{fontWeight:'900'},addToCart:{height:52,borderRadius:26,backgroundColor:C.cream,marginTop:14,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},addToCartText:{fontWeight:'900'},addToCartPrice:{color:C.pink,fontWeight:'900'},buy:{height:54,borderRadius:27,backgroundColor:C.ink,alignItems:'center',justifyContent:'center',marginTop:10,paddingHorizontal:18},buyText:{color:'#FFF',fontSize:15,fontWeight:'900'},bid:{height:52,borderRadius:26,borderWidth:1,borderColor:C.ink,alignItems:'center',justifyContent:'center',marginTop:10},bidText:{fontWeight:'900'},ask:{marginTop:22,padding:17,borderRadius:25,backgroundColor:C.cream},link:{fontWeight:'900',color:C.plum,marginTop:7}})
