import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { C } from '../constants/theme';
import { I } from '../components/Icons';
import { Avatar } from '../Avatar';
import { api } from '../lib/api';

type Product = { id: string; name: string; price: number; category?: string; sellerId?: string; image?: string; fulfillment?: string; eta?: string; stock?: number; tags?: string[] };
type Seller = { id: string; name: string; handle?: string; rating?: number; location?: string; verified?: boolean };
const fallback: Product = { id: 'p1', name: 'Silk press statement wig', price: 480, category: 'Hair', sellerId: 'u1', image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1000&q=85', fulfillment: 'local', stock: 12 };
function normalizeId(value: string | string[] | undefined) { const raw = Array.isArray(value) ? value[0] : value; if (raw === 'international') return 'p4'; if (!raw) return 'p1'; return raw.startsWith('p') ? raw : 'p' + (Number(raw) + 1); }

export default function Product() {
  const router = useRouter(); const { id } = useLocalSearchParams<{ id?: string }>(); const productId = normalizeId(id);
  const [product, setProduct] = useState<Product | null>(null); const [seller, setSeller] = useState<Seller | null>(null); const [saved, setSaved] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { let mounted = true; api<{ product: Product; seller?: Seller }>('/api/products/' + encodeURIComponent(productId)).then(result => { if (mounted) { setProduct(result.product); setSeller(result.seller || null); } }).catch(err => { if (mounted) { setProduct(fallback.id === productId ? fallback : null); setError(err instanceof Error ? err.message : 'Product could not be loaded.'); } }).finally(() => { if (mounted) setLoading(false); }); return () => { mounted = false; }; }, [productId]);
  if (loading) return <SafeAreaView style={s.safe}><View style={s.center}><ActivityIndicator color={C.pink} /><Text style={s.muted}>Loading product…</Text></View></SafeAreaView>;
  if (!product) return <SafeAreaView style={s.safe}><View style={s.center}><Text style={s.title}>Product unavailable</Text><Text style={s.muted}>{error || 'This listing is no longer available.'}</Text><Pressable onPress={() => router.back()} style={s.buy}><Text style={s.buyText}>Go back</Text></Pressable></View></SafeAreaView>;
  const price = Number(product.price || 0); const isInternational = product.fulfillment === 'international'; const sellerName = seller?.name || 'Girlies seller';
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.scroll}><View style={s.top}><Pressable onPress={() => router.back()} style={s.round}><I name="back" size={30} /></Pressable><View style={s.actions}><Pressable onPress={() => setSaved(!saved)} style={s.round}><I name="heart" size={21} color={saved ? C.pink : C.ink} /></Pressable><Pressable style={s.round}><I name="share" size={20} /></Pressable></View></View><Image source={{ uri: product.image || fallback.image }} style={s.gallery} /><View style={s.info}><View style={s.tags}><Text style={s.tag}>{isInternational ? 'INTERNATIONAL' : 'LOCAL'}</Text><Text style={s.tag}>TOP RATED</Text></View><Text style={s.title}>{product.name}</Text><Text style={s.price}>GH₵ {price.toFixed(0)}</Text><View style={s.seller}><Avatar size={45} index={0} verified={seller?.verified !== false} /><View style={{ flex: 1 }}><Text style={s.sellerName}>{sellerName} <Text style={s.blue}>✓</Text></Text><Text style={s.muted}>{seller?.rating ? seller.rating + ' · ' : ''}{seller?.location || 'Accra, Ghana'}</Text></View><Pressable style={s.follow}><Text style={s.followText}>Follow</Text></Pressable></View><Text style={s.heading}>Why girls like it</Text><Text style={s.body}>Product details, seller history and verified customer reviews appear here. Availability is checked before an order is created.</Text><View style={s.delivery}><I name="location" size={22} color={C.pink} /><View style={{ flex: 1 }}><Text style={s.deliveryTitle}>Delivery calculated at checkout</Text><Text style={s.muted}>{isInternational ? (product.eta || 'Estimated arrival shown before payment.') : 'Add your address and we’ll request a live delivery quote.'}</Text></View></View>{error ? <Text style={s.warning}>Live product data was unavailable; showing the saved listing fallback.</Text> : null}<Pressable onPress={() => router.push({ pathname: '/checkout', params: { productId: product.id } })} style={s.buy}><Text style={s.buyText}>Buy now · GH₵ {price.toFixed(0)}</Text></Pressable><Pressable onPress={() => router.push({ pathname: '/auction', params: { productId: product.id } })} style={s.bid}><Text style={s.bidText}>Place a bid</Text></Pressable><View style={s.ask}><Text style={s.heading}>Ask the girls</Text><Text style={s.body}>“Does it look better in person?” · 24 replies</Text><Pressable onPress={() => router.push('/community')}><Text style={s.link}>Join the conversation →</Text></Pressable></View></View></ScrollView></SafeAreaView>;
}
const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: C.bg }, scroll: { paddingBottom: 30 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 }, top: { padding: 15, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, actions: { flexDirection: 'row', gap: 8 }, round: { width: 43, height: 43, borderRadius: 22, backgroundColor: '#FFF', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: C.line }, gallery: { width: '100%', height: 390, resizeMode: 'cover', backgroundColor: C.rose }, info: { padding: 20 }, tags: { flexDirection: 'row', gap: 8 }, tag: { fontSize: 9, fontWeight: '900', color: C.plum, backgroundColor: C.rose, paddingHorizontal: 9, paddingVertical: 6, borderRadius: 12 }, title: { fontSize: 26, fontWeight: '900', marginTop: 10, color: C.ink, textAlign: 'center' }, price: { fontSize: 20, fontWeight: '900', marginTop: 7, textAlign: 'center' }, seller: { marginTop: 20, padding: 13, borderRadius: 24, backgroundColor: '#FFF', flexDirection: 'row', alignItems: 'center', gap: 10 }, sellerName: { fontWeight: '900', fontSize: 13 }, blue: { color: '#1877F2' }, muted: { fontSize: 11, color: C.muted, marginTop: 4, textAlign: 'center' }, follow: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 15, backgroundColor: C.cream }, followText: { fontWeight: '900', fontSize: 11 }, heading: { fontSize: 17, fontWeight: '900', marginTop: 23, marginBottom: 7 }, body: { color: C.muted, fontSize: 12, lineHeight: 18 }, delivery: { marginTop: 20, padding: 15, borderRadius: 24, backgroundColor: C.mint, flexDirection: 'row', alignItems: 'center', gap: 10 }, deliveryTitle: { fontWeight: '900' }, warning: { marginTop: 12, color: C.plum, fontSize: 11 }, buy: { height: 54, borderRadius: 27, backgroundColor: C.ink, alignItems: 'center', justifyContent: 'center', marginTop: 20, paddingHorizontal: 18 }, buyText: { color: '#FFF', fontSize: 15, fontWeight: '900' }, bid: { height: 52, borderRadius: 26, borderWidth: 1, borderColor: C.ink, alignItems: 'center', justifyContent: 'center', marginTop: 10 }, bidText: { fontWeight: '900' }, ask: { marginTop: 22, padding: 17, borderRadius: 25, backgroundColor: C.cream }, link: { fontWeight: '900', color: C.plum, marginTop: 7 } });
