import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { C } from '../constants/theme';
import { I } from '../components/Icons';
import { getSellerDashboard } from '../lib/social';

const manage = [['Products', 'shop', '/shop'], ['Orders', 'bag', '/orders'], ['Messages', 'chat', '/chat'], ['Analytics', 'chart', '/analytics']] as const;
export default function SellerStudio() {
  const router = useRouter();
  const [dashboard, setDashboard] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  useEffect(() => { getSellerDashboard().then(setDashboard).catch((loadError: any) => setError(loadError?.message || 'Could not load Seller Studio.')).finally(() => setLoading(false)); }, []);
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.scroll}><View style={s.top}><Pressable onPress={() => router.back()}><I name="back" size={34} /></Pressable><Text style={s.h}>Seller Studio</Text><View style={{ width: 24 }} /></View>
    {loading ? <View style={s.state}><ActivityIndicator color={C.pink} /></View> : error ? <View style={s.state}><Text style={s.title}>{error}</Text></View> : !dashboard ? <View style={s.state}><Text style={s.title}>No store yet</Text><Text style={s.text}>Create your store before opening seller tools.</Text><Pressable onPress={() => router.push('/seller-onboarding')} style={s.button}><Text style={s.buttonText}>Create a store</Text></Pressable></View> : <>
      <View style={s.hero}><Text style={s.k}>YOUR STORE</Text><Text style={s.storeName}>{dashboard.store.name}</Text><Text style={s.link}>{dashboard.store.slug}</Text><Pressable onPress={() => router.push({ pathname: '/seller/[id]', params: { id: dashboard.store.id } })} style={s.view}><Text style={{ fontWeight: '900' }}>View store →</Text></Pressable></View>
      <View style={s.stats}><View style={s.stat}><Text style={s.num}>GH₵ {dashboard.revenue.toLocaleString(undefined, { maximumFractionDigits: 2 })}</Text><Text style={s.label}>Recorded sales</Text></View><View style={s.stat}><Text style={s.num}>{dashboard.orderCount}</Text><Text style={s.label}>Orders</Text></View><View style={s.stat}><Text style={s.num}>{dashboard.productCount}</Text><Text style={s.label}>Products</Text></View></View>
      <Text style={s.section}>Manage</Text><View style={s.grid}>{manage.map(item => <Pressable key={item[0]} onPress={() => router.push(item[2] as any)} style={s.tile}><View style={s.tileIcon}><I name={item[1]} size={21} /></View><Text style={s.tileText}>{item[0]}</Text><I name="arrow" size={15} color={C.muted} /></Pressable>)}</View>
      <View style={s.note}><Text style={s.noteTitle}>More seller tools</Text><Text style={s.text}>Campaign, reward and monetization totals are not stored in the current database, so this screen does not show placeholder progress.</Text></View>
    </>}
  </ScrollView></SafeAreaView>;
}
const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: C.bg }, scroll: { padding: 18, paddingBottom: 30 }, top: { height: 55, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, h: { fontSize: 20, fontWeight: '900' }, hero: { marginTop: 12, padding: 22, borderRadius: 32, backgroundColor: C.plum }, k: { fontSize: 9, fontWeight: '900', letterSpacing: 1.2, color: C.sun }, storeName: { fontSize: 27, fontWeight: '900', color: '#FFF', marginTop: 7 }, link: { fontSize: 11, color: '#EADDE4', marginTop: 3 }, view: { alignSelf: 'flex-start', backgroundColor: C.sun, paddingHorizontal: 14, paddingVertical: 9, borderRadius: 18, marginTop: 15 }, stats: { marginTop: 12, flexDirection: 'row', gap: 8 }, stat: { flex: 1, padding: 15, borderRadius: 22, backgroundColor: '#FFF' }, num: { fontSize: 15, fontWeight: '900' }, label: { fontSize: 10, color: C.muted, marginTop: 3 }, section: { fontSize: 12, fontWeight: '900', color: C.muted, marginTop: 25, marginBottom: 9 }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 }, tile: { width: '48%', minHeight: 85, padding: 14, borderRadius: 24, backgroundColor: '#FFF', justifyContent: 'space-between' }, tileIcon: { width: 37, height: 37, borderRadius: 19, backgroundColor: C.cream, alignItems: 'center', justifyContent: 'center' }, tileText: { fontWeight: '900', fontSize: 12, marginTop: 8 }, note: { marginTop: 18, padding: 18, borderRadius: 25, backgroundColor: C.cream }, noteTitle: { fontSize: 16, fontWeight: '900' }, text: { fontSize: 12, lineHeight: 17, color: C.muted, marginTop: 6 }, state: { marginTop: 55, padding: 25, borderRadius: 28, backgroundColor: '#FFF', alignItems: 'center' }, title: { fontSize: 17, fontWeight: '900', textAlign: 'center' }, button: { marginTop: 15, paddingHorizontal: 22, paddingVertical: 11, borderRadius: 22, backgroundColor: C.ink }, buttonText: { color: '#FFF', fontWeight: '900' } });