import React from "react";
import { StyleSheet, View } from "react-native";
import { WebView } from "react-native-webview";

const verificationHtml = `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><style>
*{box-sizing:border-box}html,body{margin:0;background:transparent;font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#171318}body{padding:0 0 8px}.card{width:100%;border-radius:24px;background:#F5F3F4;padding:7px}.header{display:flex;justify-content:space-between;align-items:center;padding:13px 9px}.title{font-size:17px;font-weight:500;letter-spacing:-.5px}.billing-toggle{position:relative;display:flex;background:#E5E1E3;border-radius:18px;padding:3px}.billing-indicator{position:absolute;left:3px;top:3px;width:72px;height:29px;border-radius:15px;background:#FFF;transition:transform .35s cubic-bezier(.34,1.56,.64,1)}.billing-button{position:relative;z-index:1;width:72px;padding:7px 0;border:0;background:transparent;border-radius:15px;font-size:8px;font-weight:900;letter-spacing:1px;color:#999}.billing-button.active{color:#F64D86}.plan-list{display:flex;flex-direction:column;gap:6px}.plan{border-radius:18px;background:#FFF;padding:14px;border:1px solid #E5E1E3;transition:border-color .25s,box-shadow .25s}.plan.selected{border-color:#F64D86;box-shadow:0 2px 10px rgba(246,77,134,.12)}.plan-top{display:flex;justify-content:space-between;gap:8px}.plan-info{display:flex;flex:1;gap:10px}.radio{width:19px;height:19px;flex:none;border-radius:50%;border:1.5px solid #CCC;display:flex;align-items:center;justify-content:center;transition:background .25s,border-color .25s}.radio.selected{border-color:#F64D86;background:#F64D86;color:#FFF}.radio.selected:after{content:"✓";font-size:11px;font-weight:900}.plan-copy{flex:1}.name-row{display:flex;align-items:center;gap:7px}.plan-name{font-size:15px;font-weight:500}.badge{font-size:8px;font-weight:900;color:#F64D86;background:#FFF0F6;padding:3px 7px;border-radius:9px;text-transform:uppercase}.description{font-size:10px;color:#999;line-height:15px;margin-top:5px}.price{text-align:right}.price-text{font-size:15px;font-weight:500}.per-user{font-size:8px;font-weight:900;letter-spacing:1px;color:#AAA;margin-top:4px}.features{border-top:1px solid #EEE;margin-top:13px;padding-top:13px;display:flex;flex-direction:column;gap:8px;animation:reveal .3s ease}.features-label{font-size:9px;font-weight:900;letter-spacing:1px;color:#AAA;text-transform:uppercase;margin-bottom:2px}.feature-row{display:flex;align-items:center;gap:8px}.feature-check{color:#F64D86;font-size:14px;font-weight:900}.feature-text{font-size:11px;color:#666;flex:1}.footer{display:flex;flex-direction:column;align-items:center;gap:10px;padding:15px 9px}.footer-text{font-size:9px;color:#AAA;text-align:center}.continue{min-height:42px;padding:0 28px;border:0;border-radius:22px;background:#F64D86;color:#FFF;font-size:13px;font-weight:500}.hidden{display:none}@keyframes reveal{from{opacity:0;transform:translateY(-4px)}to{opacity:1;transform:none}}
</style></head><body><div class="card"><div class="header"><div class="title">Select a plan</div><div class="billing-toggle"><div id="billing-indicator" class="billing-indicator"></div><button class="billing-button active" data-cycle="monthly">MONTHLY</button><button class="billing-button" data-cycle="yearly">YEARLY</button></div></div><div class="plan-list">
<div class="plan selected" data-plan="verified"><div class="plan-top"><div class="plan-info"><div class="radio selected"></div><div class="plan-copy"><div class="name-row"><div class="plan-name">Verified</div><div class="badge">Popular</div></div><div class="description">Build trust with a verified seller profile.</div></div></div><div class="price"><div class="price-text" data-monthly="GH₵ 49" data-yearly="GH₵ 39">GH₵ 49</div><div class="per-user">PER USER / MONTH</div></div></div><div class="features"><div class="features-label">Includes</div><div class="feature-row"><span class="feature-check">✓</span><span class="feature-text">Verification badge on your seller profile</span></div><div class="feature-row"><span class="feature-check">✓</span><span class="feature-text">Priority discovery in marketplace search</span></div><div class="feature-row"><span class="feature-check">✓</span><span class="feature-text">Seller profile trust insights</span></div></div></div>
<div class="plan" data-plan="verified-plus"><div class="plan-top"><div class="plan-info"><div class="radio"></div><div class="plan-copy"><div class="name-row"><div class="plan-name">Verified Plus</div><div class="badge">Best value</div></div><div class="description">More visibility and tools for growing sellers.</div></div></div><div class="price"><div class="price-text" data-monthly="GH₵ 99" data-yearly="GH₵ 79">GH₵ 99</div><div class="per-user">PER USER / MONTH</div></div></div><div class="features hidden"><div class="features-label">Everything in Verified, plus</div><div class="feature-row"><span class="feature-check">✓</span><span class="feature-text">Featured placement opportunities</span></div><div class="feature-row"><span class="feature-check">✓</span><span class="feature-text">Advanced audience insights</span></div><div class="feature-row"><span class="feature-check">✓</span><span class="feature-text">Priority seller support</span></div></div></div>
</div><div class="footer"><div class="footer-text">Cancel anytime. No long-term contract.</div><button class="continue">Continue</button></div></div><script>
const indicator=document.getElementById("billing-indicator");const cycles=[...document.querySelectorAll("[data-cycle]")];const prices=[...document.querySelectorAll(".price-text")];cycles.forEach((button,index)=>button.addEventListener("click",()=>{indicator.style.transform="translateX("+index*72+"px)";cycles.forEach(item=>item.classList.toggle("active",item===button));prices.forEach(price=>price.textContent=price.dataset[index?"yearly":"monthly"])}));document.querySelectorAll(".plan").forEach(plan=>plan.addEventListener("click",()=>{document.querySelectorAll(".plan").forEach(item=>{const selected=item===plan;item.classList.toggle("selected",selected);item.querySelector(".radio").classList.toggle("selected",selected);item.querySelector(".features").classList.toggle("hidden",!selected)})}));
</script></body></html>`;

export default function SellerVerificationScreen() {
  return (
    <View style={s.wrap}>
      <WebView
        originWhitelist={["*"]}
        source={{ html: verificationHtml }}
        javaScriptEnabled
        scrollEnabled={false}
        showsVerticalScrollIndicator={false}
        showsHorizontalScrollIndicator={false}
        style={s.webView}
      />
    </View>
  );
}

const s = StyleSheet.create({
  wrap: { width: "100%" },
  webView: { width: "100%", height: 490, backgroundColor: "transparent" },
});