import React,{useCallback,useEffect,useState}from'react';
import{SafeAreaView}from'react-native-safe-area-context';
import{View,Text,Pressable,TextInput,ScrollView,StyleSheet,ActivityIndicator,Alert}from'react-native';
import{useRouter,useLocalSearchParams}from'expo-router';
import{C}from'../../constants/theme';
import{I}from'../../components/Icons';
import{Avatar}from'../../Avatar';
import{getConversation,sendMessage}from'../../lib/social';

type Msg={id:string;sender_id:string;body:string|null;media:any;created_at:string;status:string};
export default function Conversation(){
 const r=useRouter();const{id}=useLocalSearchParams<{id?:string}>();const[text,setText]=useState('');const[msgs,setMsgs]=useState<Msg[]>([]);const[meId,setMeId]=useState('');const[name,setName]=useState('Conversation');const[avatar,setAvatar]=useState<string|null>(null);const[verified,setVerified]=useState(false);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{if(!id||Array.isArray(id))return;setLoading(true);try{const data=await getConversation(id);setMeId(data.meId);setMsgs(data.messages as Msg[]);setName(data.profile?.display_name||'Conversation');setAvatar(data.profile?.avatar_url||null);setVerified(Boolean(data.profile?.verified));}catch(e:any){Alert.alert('Could not open chat',e?.message||'Please try again.');r.back();}finally{setLoading(false);}},[id,r]);
 useEffect(()=>{void load();},[load]);
 const send=async()=>{if(!id||Array.isArray(id)||!text.trim()||busy)return;const body=text.trim();setText('');setBusy(true);try{const message=await sendMessage(id,body);if(message)setMsgs(current=>[...current,message as Msg]);}catch(e:any){setText(body);Alert.alert('Message failed',e?.message||'Could not send your message.');}finally{setBusy(false);}};
 return <SafeAreaView style={s.safe}><View style={s.head}><Pressable onPress={()=>r.back()}><I name="back" size={34}/></Pressable><Avatar size={43} uri={avatar} verified={verified}/><View style={{flex:1}}><Text style={s.name}>{name}</Text><Text style={s.online}>online now</Text></View><I name="chat" size={22}/></View>{loading?<View style={s.loading}><ActivityIndicator color={C.pink}/></View>:<><ScrollView contentContainerStyle={s.messages}>{msgs.map((m,i)=><View key={m.id||String(i)} style={[s.bubble,m.sender_id===meId?s.me:s.them]}><Text style={{fontSize:14,lineHeight:19,color:m.sender_id===meId?'#FFF':C.ink}}>{m.body||'Media'}</Text></View>)}<Pressable onPress={()=>r.push('/lumi')} style={s.lumi}><Text>🪄</Text><Text style={{fontWeight:'800',fontSize:11}}>Ask Lumi in this chat</Text></Pressable></ScrollView><View style={s.composer}><Pressable><I name="plus" size={22}/></Pressable><TextInput value={text} onChangeText={setText} placeholder="Message…" style={s.input} editable={!busy}/><Pressable><I name="mic" size={18}/></Pressable><Pressable onPress={send} style={s.send}><I name="send" size={16} color="#FFF"/></Pressable></View></>}</SafeAreaView>};
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},head:{height:68,paddingHorizontal:15,flexDirection:'row',alignItems:'center',gap:10,borderBottomWidth:1,borderBottomColor:C.line},name:{fontSize:14,fontWeight:'900'},online:{fontSize:10,color:C.green,marginTop:2},messages:{padding:17},bubble:{padding:13,borderRadius:22,maxWidth:'80%',marginBottom:8},me:{alignSelf:'flex-end',backgroundColor:C.plum,borderBottomRightRadius:5},them:{alignSelf:'flex-start',backgroundColor:'#FFF',borderBottomLeftRadius:5,borderWidth:1,borderColor:C.line},lumi:{alignSelf:'center',flexDirection:'row',gap:8,padding:10,borderRadius:18,backgroundColor:C.cream,marginTop:10},composer:{minHeight:61,margin:10,borderRadius:31,backgroundColor:'#FFF',borderWidth:1,borderColor:C.line,flexDirection:'row',alignItems:'center',paddingHorizontal:11,gap:8},input:{flex:1,fontSize:14},send:{width:39,height:39,borderRadius:20,backgroundColor:C.pink,alignItems:'center',justifyContent:'center'},loading:{flex:1,alignItems:'center',justifyContent:'center'}});
