import React, { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useFocusEffect, useLocalSearchParams, useRouter } from 'expo-router';
import { C } from '../../constants/theme';
import { I } from '../../components/Icons';
import { getProducts, getSellerStudioMetrics, getServices, getStore, type ProductRecord, type SellerStudioMetrics, type ServiceRecord } from '../../lib/social';
const money = (value: number) => 'GH₵ ' + Number(value || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const titles: Record<string, string> = { analytics:'Analytics', balance:'Balance & Payouts', catalog:'Catalog', orders:'Orders', customers:'Customers', 'product-analytics':'Product Analytics', gifts:'Gifts', referrals:'Referrals', monetization:'Monetization', promotions:'Promotions', messages:'Messages', settings:'Seller Settings' };
const subtitles: Record<string, string> = { analytics:'Track the full funnel using verified marketplace events.', balance:'Money earned from paid orders and recorded withdrawals.', catalog:'Products, services, collections and inventory.', orders:'Every order returned by the live store order ledger.', customers:'Customer totals from paid orders.', 'product-analytics':'Product inventory and recorded activity.', gifts:'Gift performance will appear when gift transactions are connected.', referrals:'Referral clicks and earnings will appear from tracked referral events.', monetization:'Eligibility and earnings are calculated from configured seller rules.', promotions:'Campaign performance will appear when promotions are connected.', messages:'Continue conversations with customers.', settings:'Payout, business, notification and seller preferences.' };
const ranges = [[7,'7D'],[30,'30D'],[90,'90D'],[365,'1Y']] as const;
export default function SellerStudioSection() {
  const router = useRouter(); const { section: raw } = useLocalSearchParams<{ section?: string }>(); const section = Array.isArray(raw) ? raw[0] : raw || 'analytics';
  const [store,setStore]=useState<any>(null); const [metrics,setMetrics]=useState<SellerStudioMetrics|null>(null); const [products,setProducts]=useState<ProductRecord[]>([]); const [services,setServices]=useState<ServiceRecord[]>([]); const [days,setDays]=useState(30); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const load=useCallback(async()=>{try{setLoading(true);setError('');const shop=await getStore('me');setStore(shop);if(shop){const [live,items,serviceRows]=await Promise.all([getSellerStudioMetrics(shop.id,days),getProducts(200,{storeId:shop.id,includeOutOfStock:true}),getServices(shop.owner_id)]);setMetrics(live);setProducts(items);setServices(serviceRows);}}catch(e:any){setError(e?.message||'Could not load this seller view.');}finally{setLoading(false);}},[days]);
  useFocusEffect(useCallback(()=>{void load();},[load]));
  if(loading)return <SafeAreaView style={s.safe}><View style={s.center}><ActivityIndicator color={C.pink}/></View></SafeAreaView>;
  if(!store||!metrics)return <SafeAreaView style={s.safe}><View style={s.center}><Text style={s.title}>Seller data unavailable</Text><Text style={s.muted}>{error||'Open a shop before using Seller Studio.'}</Text></View></SafeAreaView>;
  const conversion=metrics.visitors?((metrics.purchases/metrics.visitors)*100).toFixed(1)+'%':'0.0%';
  const rows=metrics.transactions||[];
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.scroll} showsVerticalScrollIndicator={false}><View style={s.top}><Pressable onPress={()=>router.back()}><I name="back" size={30}/></Pressable><Text style={s.h}>{titles[section]||'Seller Studio'}</Text><Pressable onPress={()=>router.push('/seller-studio/settings')}><I name="settings" size={22}/></Pressable></View><Text style={s.subtitle}>{subtitles[section]||subtitles.analytics}</Text>{error&&<View style={s.error}><Text style={s.errorText}>{error}</Text><Pressable onPress={load}><Text style={s.retry}>Retry</Text></Pressable></View>}
  {(section==='analytics'||section==='product-analytics'||section==='customers')&&<View style={s.rangeRow}>{ranges.map(([value,label])=><Pressable key={value} style={[s.range,days===value&&s.rangeOn]} onPress={()=>setDays(value)}><Text style={[s.rangeText,days===value&&s.rangeTextOn]}>{label}</Text></Pressable>)}</View>}
  {section==='analytics'&&<><View style={s.grid}>{[['Revenue',money(metrics.gross_revenue)],['Orders',String(metrics.orders)],['Visitors',String(metrics.visitors)],['Conversion',conversion],['Views',String(metrics.views)],['Engagement',String(metrics.engagement)],['Clicks',String(metrics.clicks)],['Purchases',String(metrics.purchases)]].map(([label,value])=><Pressable key={label} style={s.card}><Text style={s.big}>{value}</Text><Text style={s.label}>{label}</Text><I name="forward" size={15} color={C.muted}/></Pressable>)}</View><View style={s.funnel}>{[['Impressions',metrics.views],['Views',metrics.views],['Engagement',metrics.engagement],['Product clicks',metrics.clicks],['Cart',metrics.carts],['Checkout',metrics.checkouts],['Purchase',metrics.purchases]].map(([label,value])=><View key={String(label)} style={s.funnelRow}><Text style={s.funnelLabel}>{label}</Text><Text style={s.funnelValue}>{String(value)}</Text></View>)}</View><Text style={s.note}>Every value above is read from Supabase events and paid orders for {store.name}. No demo values are inserted.</Text></>}
  {section==='balance'&&<><View style={s.grid}>{[['Available balance',money(metrics.gross_revenue-metrics.withdrawn)],['Pending balance',money(metrics.pending_revenue)],['Lifetime earnings',money(metrics.gross_revenue)],['Withdrawals',money(metrics.withdrawn)]].map(([label,value])=><View key={label} style={s.card}><Text style={s.big}>{value}</Text><Text style={s.label}>{label}</Text></View>)}</View><Text style={s.section}>Transactions</Text>{rows.length?rows.map(row=><View key={row.id} style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>{money(row.amount)}</Text><Text style={s.muted}>{row.status} · {new Date(row.created_at).toLocaleDateString()}</Text></View><Text style={s.status}>{row.fulfillment_status}</Text></View>):<Empty text="No order transactions have been recorded for this shop yet."/>}</>}
  {section==='catalog'&&<><View style={s.actionRow}><Pressable style={s.action} onPress={()=>router.push('/product-editor')}><I name="plus" size={19} color="#FFF"/><Text style={s.actionText}>Add product</Text></Pressable><Pressable style={s.actionLight} onPress={()=>router.push('/service-editor')}><I name="plus" size={19} color={C.ink}/><Text style={s.actionLightText}>Add service</Text></Pressable></View><Text style={s.section}>Products · {products.length}</Text>{products.map(product=><Pressable key={product.id} style={s.row} onPress={()=>router.push({pathname:'/product-editor',params:{id:product.id}})}><View style={{flex:1}}><Text style={s.rowTitle}>{product.name}</Text><Text style={s.muted}>{product.category} · {product.stock_status==='out_of_stock'?'Out of stock':String(product.stock)+' in stock'}</Text></View><Text style={s.status}>Edit</Text></Pressable>)}<Text style={s.section}>Services · {services.length}</Text>{services.map(service=><Pressable key={service.id} style={s.row} onPress={()=>router.push({pathname:'/service-editor',params:{id:service.id}})}><View style={{flex:1}}><Text style={s.rowTitle}>{service.name}</Text><Text style={s.muted}>{service.category} · {service.duration_minutes} min</Text></View><Text style={s.status}>Edit</Text></Pressable>)}</>}
  {section==='orders'&&<>{rows.length?rows.map(row=><Pressable key={row.id} style={s.row} onPress={()=>router.push('/orders')}><View style={{flex:1}}><Text style={s.rowTitle}>{money(row.amount)}</Text><Text style={s.muted}>{new Date(row.created_at).toLocaleDateString()} · {row.status}</Text></View><Text style={s.status}>{row.fulfillment_status}</Text></Pressable>):<Empty text="No orders have been recorded for this shop yet."/>}</>}
  {section==='customers'&&<View style={s.card}><Text style={s.big}>{metrics.customers}</Text><Text style={s.label}>Customers with paid orders in range</Text><Text style={s.note}>New vs returning breakdown will appear as customer purchase history grows.</Text></View>}
  {section==='product-analytics'&&<>{products.map(product=><View key={product.id} style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>{product.name}</Text><Text style={s.muted}>{product.stock} in stock · {product.category}</Text></View><Text style={s.status}>Views tracked live</Text></View>)}{!products.length&&<Empty text="No products are listed yet."/>}</>}
  {['gifts','referrals','monetization','promotions'].includes(section)&&<Empty text={subtitles[section]}/>} {section==='messages'&&<Pressable style={s.action} onPress={()=>router.push('/chat')}><I name="chat" size={19} color="#FFF"/><Text style={s.actionText}>Open messages</Text></Pressable>} {section==='settings'&&<><Pressable style={s.row} onPress={()=>router.push('/shop-editor')}><Text style={s.rowTitle}>Business and storefront</Text><I name="forward" size={19}/></Pressable><Pressable style={s.row} onPress={()=>router.push('/settings')}><Text style={s.rowTitle}>Account and notifications</Text><I name="forward" size={19}/></Pressable></>}
  </ScrollView></SafeAreaView>;
}
function Empty({text}:{text:string}){return <View style={s.empty}><Text style={s.emptyIcon}>✦</Text><Text style={s.emptyTitle}>No live records yet</Text><Text style={s.muted}>{text}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},scroll:{padding:18,paddingBottom:55},center:{flex:1,alignItems:'center',justifyContent:'center',padding:24},top:{height:55,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},h:{fontSize:20,fontWeight:'900'},subtitle:{fontSize:12,color:C.muted,lineHeight:18,marginTop:12,marginBottom:14},rangeRow:{flexDirection:'row',gap:7,marginBottom:14},range:{flex:1,height:38,borderRadius:19,backgroundColor:'#FFF',alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:C.line},rangeOn:{backgroundColor:C.ink,borderColor:C.ink},rangeText:{fontSize:11,fontWeight:'900'},rangeTextOn:{color:'#FFF'},grid:{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between',gap:9},card:{width:'48%',minHeight:88,borderRadius:21,backgroundColor:'#FFF',padding:14},big:{fontSize:17,fontWeight:'900'},label:{fontSize:11,color:C.muted,marginTop:5},funnel:{marginTop:16,padding:16,borderRadius:24,backgroundColor:C.ink,gap:7},funnelRow:{flexDirection:'row',justifyContent:'space-between',paddingBottom:7,borderBottomWidth:1,borderBottomColor:'#FFFFFF22'},funnelLabel:{fontSize:12,color:'#F4E7EF'},funnelValue:{fontSize:12,fontWeight:'900',color:'#FFF'},note:{fontSize:11,lineHeight:17,color:C.muted,marginTop:14},section:{fontSize:17,fontWeight:'900',marginTop:22,marginBottom:9},row:{minHeight:64,borderRadius:20,backgroundColor:'#FFF',padding:13,marginBottom:8,flexDirection:'row',alignItems:'center',gap:10},rowTitle:{fontSize:13,fontWeight:'900'},status:{color:C.pink,fontSize:11,fontWeight:'900'},actionRow:{flexDirection:'row',gap:9},action:{height:50,borderRadius:25,backgroundColor:C.pink,flex:1,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7},actionLight:{height:50,borderRadius:25,backgroundColor:'#FFF',borderWidth:1,borderColor:C.line,flex:1,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7},actionText:{color:'#FFF',fontWeight:'900'},actionLightText:{fontWeight:'900'},empty:{padding:25,borderRadius:24,backgroundColor:'#FFF',alignItems:'center'},emptyIcon:{fontSize:30,color:C.pink},emptyTitle:{fontSize:16,fontWeight:'900',marginTop:6},muted:{fontSize:11,color:C.muted,marginTop:4},error:{padding:14,borderRadius:18,backgroundColor:'#FFF0F1'},errorText:{fontSize:12,color:C.red},retry:{color:C.pink,fontWeight:'900',marginTop:7},title:{fontSize:18,fontWeight:'900'}});