export type CategoryDefinition = {
  slug: string;
  label: string;
  subtitle: string;
  icon: string;
  color: string;
  image: string;
  subcategories: string[];
};

export const MARKETPLACE_CATEGORIES: CategoryDefinition[] = [
  { slug: 'hair', label: 'Hair', subtitle: 'Wigs, braids & bundles', icon: 'hair', color: '#FFB7C9', image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1000&q=85', subcategories: ['Wigs', 'Bundles', 'Braids', 'Closures', 'Hair care'] },
  { slug: 'beauty', label: 'Beauty', subtitle: 'Makeup, skincare & glow', icon: 'beauty', color: '#FFD45A', image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=1000&q=85', subcategories: ['Makeup', 'Skincare', 'Body care', 'Tools', 'Nails'] },
  { slug: 'fashion', label: 'Fashion', subtitle: 'Looks for every plan', icon: 'fashion', color: '#B89CFF', image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1000&q=85', subcategories: ['Dresses', 'Tops', 'Shoes', 'Bags', 'Jewellery'] },
  { slug: 'fragrance', label: 'Fragrance', subtitle: 'Scents that stay', icon: 'fragrance', color: '#8EDBC2', image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=1000&q=85', subcategories: ['Perfume', 'Body mist', 'Oils', 'Gift sets', 'Home scent'] },
  { slug: 'gadgets', label: 'Gadgets', subtitle: 'Phones, tech & accessories', icon: 'gadgets', color: '#A7DDF2', image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1000&q=85', subcategories: ['Phones', 'Audio', 'Smart watches', 'Gaming', 'Accessories'] },
  { slug: 'home-appliances', label: 'Home appliances', subtitle: 'Useful things for home', icon: 'appliances', color: '#CBEA9C', image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1000&q=85', subcategories: ['Kitchen', 'Cleaning', 'Cooling', 'Small appliances', 'Electronics'] },
  { slug: 'furniture', label: 'Furniture', subtitle: 'Pieces with personality', icon: 'furniture', color: '#F4B49F', image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1000&q=85', subcategories: ['Living room', 'Bedroom', 'Dining', 'Office', 'Decor'] },
  { slug: 'intimates', label: 'Intimates', subtitle: 'Private care & pleasure', icon: 'intimates', color: '#F6A7D4', image: 'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?auto=format&fit=crop&w=1000&q=85', subcategories: ['Lingerie', 'Wellness', 'Body care', 'Accessories', 'Gift sets'] },
  { slug: 'vehicles-auto', label: 'Vehicles & Auto', subtitle: 'Cars, bikes, parts & tyres', icon: 'vehicles', color: '#B8D7F2', image: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1000&q=85', subcategories: ['Cars', 'Motorcycles', 'Parts', 'Tyres', 'Accessories'] },
  { slug: 'property-real-estate', label: 'Property & Real Estate', subtitle: 'Homes, land & rentals', icon: 'property', color: '#D9C7A8', image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=85', subcategories: ['Houses', 'Apartments', 'Land', 'Rentals', 'Commercial property'] },
  { slug: 'kids-baby', label: 'Kids & Baby', subtitle: 'Play, learn & grow', icon: 'kids', color: '#F7D58A', image: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&w=1000&q=85', subcategories: ['Toys', 'Baby equipment', 'School supplies', 'Kids clothing', 'Kids products'] },
  { slug: 'services', label: 'Services', subtitle: 'Trusted help for every plan', icon: 'services', color: '#F6A7D4', image: 'https://raw.githubusercontent.com/Buildrco/Girlies-App/main/app/assets/category-services.png', subcategories: ['Repairs', 'Cleaning', 'Beauty services', 'Photography', 'Delivery', 'Professionals'] },
  { slug: 'groceries-food', label: 'Groceries & Food', subtitle: 'Fresh food for your everyday', icon: 'groceries', color: '#BDE7A5', image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1000&q=85', subcategories: ['Fresh produce', 'Pantry', 'Drinks', 'Baked goods', 'Ready meals'] },
  { slug: 'jewelry-watches', label: 'Jewelry & Watches', subtitle: 'Pieces worth keeping', icon: 'jewelry', color: '#F4C36A', image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1000&q=85', subcategories: ['Necklaces', 'Earrings', 'Rings', 'Bracelets', 'Watches'] },
  { slug: 'sports-fitness', label: 'Sports & Fitness', subtitle: 'Move in your own way', icon: 'sports', color: '#A9D7C2', image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1000&q=85', subcategories: ['Gym equipment', 'Activewear', 'Running', 'Team sports', 'Wellness'] },
  { slug: 'books-stationery', label: 'Books & Stationery', subtitle: 'Ideas, notes & stories', icon: 'books', color: '#C7B7E8', image: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=1000&q=85', subcategories: ['Books', 'Notebooks', 'Writing', 'Art supplies', 'Office supplies'] },
  { slug: 'pets-supplies', label: 'Pets & Supplies', subtitle: 'Good things for good companions', icon: 'pets', color: '#EFC2AA', image: 'https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=1000&q=85', subcategories: ['Dogs', 'Cats', 'Food', 'Grooming', 'Accessories'] },
  { slug: 'agriculture-farm-supplies', label: 'Agriculture & Farm Supplies', subtitle: 'Grow, raise & harvest', icon: 'agriculture', color: '#B9D89B', image: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=1000&q=85', subcategories: ['Seeds', 'Fertilizer', 'Tools', 'Livestock', 'Farm equipment'] },
  { slug: 'tools-hardware', label: 'Tools & Hardware', subtitle: 'Build, fix & make', icon: 'tools', color: '#D5C0A4', image: 'https://images.unsplash.com/photo-1530124566582-a618bc2615dc?auto=format&fit=crop&w=1000&q=85', subcategories: ['Hand tools', 'Power tools', 'Hardware', 'Safety', 'Building supplies'] },
  { slug: 'business-industrial', label: 'Business & Industrial', subtitle: 'Equipment for serious work', icon: 'business', color: '#B8C6D9', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=1000&q=85', subcategories: ['Office equipment', 'Machinery', 'Restaurant supplies', 'Packaging', 'Wholesale'] },
  { slug: 'digital-products', label: 'Digital Products', subtitle: 'Downloads, templates & tools', icon: 'digital', color: '#C4D1F7', image: 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?auto=format&fit=crop&w=1000&q=85', subcategories: ['Templates', 'Courses', 'E-books', 'Software', 'Presets'] },
];


export const MAIN_CATEGORIES: CategoryDefinition[] = [
  { slug: 'shop', label: 'SHOP', subtitle: 'Products, sellers & everyday finds', icon: 'shop', color: '#FFD45A', image: 'https://raw.githubusercontent.com/Buildrco/Girlies-App/main/app/assets/category-shop.png', subcategories: [] },
  { slug: 'services', label: 'SERVICES', subtitle: 'Trusted help for every plan', icon: 'services', color: '#BDE7A5', image: 'https://raw.githubusercontent.com/Buildrco/Girlies-App/main/app/assets/category-services.png', subcategories: ['Beauty & Grooming', 'Home & Cleaning', 'Repairs & Maintenance', 'Construction & Skilled Trades', 'Photography & Video', 'Design & Creative', 'Technology & Digital', 'Business & Professional', 'Education & Tutoring', 'Events & Entertainment', 'Transport & Delivery', 'Health & Wellness', 'Personal Services', 'Other'] },
  { slug: 'events', label: 'EVENTS', subtitle: 'Plans, places & people to see', icon: 'events', color: '#FFB7C9', image: 'https://raw.githubusercontent.com/Buildrco/Girlies-App/main/app/assets/category-events.png', subcategories: ['Entertainment', 'Music', 'Sports', 'Education & Learning', 'Business & Networking', 'Religious & Spiritual', 'Arts & Culture', 'Food & Culinary', 'Fashion & Beauty', 'Community', 'Family & Social', 'Health & Wellness', 'Technology', 'Conferences & Exhibitions', 'Charity & Fundraising', 'Other'] },
  { slug: 'jobs-careers', label: 'JOBS & CAREERS', subtitle: 'Opportunities for your next chapter', icon: 'jobs', color: '#B8D7F2', image: 'https://raw.githubusercontent.com/Buildrco/Girlies-App/main/app/assets/category-jobs.png', subcategories: ['Administration & Office', 'Accounting & Finance', 'Sales & Marketing', 'Technology & IT', 'Design & Creative', 'Media & Communications', 'Engineering', 'Healthcare', 'Education', 'Hospitality & Tourism', 'Construction & Skilled Trades', 'Transport & Logistics', 'Retail & Customer Service', 'Legal & Professional', 'Agriculture', 'Government & NGO', 'Other'] },
  { slug: 'property', label: 'PROPERTY', subtitle: 'Homes, land & spaces to make yours', icon: 'property', color: '#D9C7A8', image: 'https://raw.githubusercontent.com/Buildrco/Girlies-App/main/app/assets/category-property.png', subcategories: ['Houses', 'Apartments', 'Land', 'Commercial Property', 'Offices', 'Shops & Retail', 'Warehouses', 'Industrial Property', 'Student Accommodation', 'Short-Stay', 'Other'] },
  { slug: 'vehicles', label: 'VEHICLES', subtitle: 'Cars, bikes & everything that moves', icon: 'vehicles', color: '#B89CFF', image: 'https://raw.githubusercontent.com/Buildrco/Girlies-App/main/app/assets/category-vehicles.png', subcategories: ['Cars', 'Motorcycles', 'Trucks', 'Vans', 'Buses', 'Trailers', 'Heavy Equipment', 'Boats', 'Other'] },
];

export function getCategory(slug: string) {
  return MARKETPLACE_CATEGORIES.find(category => category.slug === slug) || MAIN_CATEGORIES.find(category => category.slug === slug) || MARKETPLACE_CATEGORIES[0];
}
