create table if not exists public.seller_announcements (id uuid primary key default gen_random_uuid(), store_id uuid not null references public.stores(id) on delete cascade, author_id uuid not null references public.profiles(id) on delete cascade, title text not null, body text not null, publish_to_feed boolean not null default false, published boolean not null default true, created_at timestamptz not null default now());
create index if not exists seller_announcements_store_idx on public.seller_announcements(store_id,created_at desc);
create table if not exists public.seller_campaigns (id uuid primary key default gen_random_uuid(), store_id uuid not null references public.stores(id) on delete cascade, owner_id uuid not null references public.profiles(id) on delete cascade, name text not null, message text not null, audience text not null default 'all', created_at timestamptz not null default now());
create table if not exists public.seller_discounts (id uuid primary key default gen_random_uuid(), store_id uuid not null references public.stores(id) on delete cascade, owner_id uuid not null references public.profiles(id) on delete cascade, title text not null, code text, percent_off numeric(5,2) not null check (percent_off >= 0 and percent_off <= 100), active boolean not null default true, created_at timestamptz not null default now());
alter table public.seller_announcements enable row level security; alter table public.seller_campaigns enable row level security; alter table public.seller_discounts enable row level security;
drop policy if exists seller_announcements_public_read on public.seller_announcements; create policy seller_announcements_public_read on public.seller_announcements for select using (published = true or author_id = auth.uid());
drop policy if exists seller_announcements_owner_insert on public.seller_announcements; create policy seller_announcements_owner_insert on public.seller_announcements for insert with check (author_id = auth.uid() and exists (select 1 from public.stores s where s.id=store_id and s.owner_id=auth.uid()));
drop policy if exists seller_announcements_owner_update on public.seller_announcements; create policy seller_announcements_owner_update on public.seller_announcements for update using (author_id = auth.uid());
drop policy if exists seller_campaigns_owner_all on public.seller_campaigns; create policy seller_campaigns_owner_all on public.seller_campaigns for all using (owner_id=auth.uid()) with check (owner_id=auth.uid());
drop policy if exists seller_discounts_owner_all on public.seller_discounts; create policy seller_discounts_owner_all on public.seller_discounts for all using (owner_id=auth.uid()) with check (owner_id=auth.uid());
create or replace function public.get_seller_studio_customers(p_store_id uuid) returns table(customer_id uuid, display_name text, handle text, avatar_url text, product_id uuid, product_name text, product_image text, quantity integer, purchased_at timestamptz) language plpgsql security definer set search_path = public as $$
declare v_owner_id uuid;
begin
 select s.owner_id into v_owner_id from public.stores s where s.id=p_store_id;
 if v_owner_id is null or v_owner_id <> auth.uid() then raise exception 'Not allowed'; end if;
 return query select o.buyer_id, coalesce(pr.display_name,pr.handle,'Customer'), pr.handle, pr.avatar_url, p.id, p.name, p.image_urls[1], o.quantity, o.created_at from public.orders o join public.profiles pr on pr.id=o.buyer_id left join public.products p on p.id=o.product_id where o.store_id=p_store_id and o.buyer_id is not null and lower(coalesce(o.payment_status,'')) in ('paid','success','successful','completed') order by o.created_at desc;
end; $$;
grant execute on function public.get_seller_studio_customers(uuid) to authenticated;