create table if not exists public.seller_events (id uuid primary key default gen_random_uuid(), store_id uuid not null references public.stores(id) on delete cascade, product_id uuid references public.products(id) on delete cascade, actor_id uuid references public.profiles(id) on delete set null, session_id text, event_type text not null check (event_type in ('impression','view','engagement','product_click','cart','checkout','purchase')), source text not null default 'Shop', metadata jsonb not null default '{}', created_at timestamptz not null default now());
create index if not exists seller_events_store_created_idx on public.seller_events(store_id, created_at desc);
create index if not exists seller_events_product_idx on public.seller_events(product_id, event_type, created_at desc);
create table if not exists public.seller_payouts (id uuid primary key default gen_random_uuid(), store_id uuid not null references public.stores(id) on delete cascade, amount numeric(12,2) not null check (amount >= 0), status text not null default 'pending', reference text unique, created_at timestamptz not null default now());
create index if not exists seller_payouts_store_created_idx on public.seller_payouts(store_id, created_at desc);
alter table public.seller_events enable row level security;
alter table public.seller_payouts enable row level security;
drop policy if exists seller_events_insert_own on public.seller_events;
create policy seller_events_insert_own on public.seller_events for insert with check (actor_id is null or auth.uid() = actor_id);
drop policy if exists seller_events_read_owner on public.seller_events;
create policy seller_events_read_owner on public.seller_events for select using (exists (select 1 from public.stores s where s.id = store_id and s.owner_id = auth.uid()));
drop policy if exists seller_payouts_read_owner on public.seller_payouts;
create policy seller_payouts_read_owner on public.seller_payouts for select using (exists (select 1 from public.stores s where s.id = store_id and s.owner_id = auth.uid()));
create or replace function public.get_seller_studio_metrics(p_store_id uuid, p_start timestamptz default now() - interval '30 days', p_end timestamptz default now()) returns jsonb language plpgsql security definer set search_path = public as $$
declare result jsonb; v_owner_id uuid;
begin
 select s.owner_id into v_owner_id from public.stores s where s.id=p_store_id;
 if v_owner_id is null or v_owner_id <> auth.uid() then raise exception 'Not allowed'; end if;
 select jsonb_build_object('products',(select count(*) from public.products p where p.store_id=p_store_id),'services',(select count(*) from public.services srv where srv.owner_id=v_owner_id),'orders',(select count(*) from public.orders o where o.store_id=p_store_id and o.created_at between p_start and p_end),'paid_orders',(select count(*) from public.orders o where o.store_id=p_store_id and o.created_at between p_start and p_end and lower(coalesce(o.payment_status,'')) in ('paid','success','successful','completed')),'gross_revenue',coalesce((select sum(o.subtotal) from public.orders o where o.store_id=p_store_id and o.created_at between p_start and p_end and lower(coalesce(o.payment_status,'')) in ('paid','success','successful','completed')),0),'pending_revenue',coalesce((select sum(o.subtotal) from public.orders o where o.store_id=p_store_id and o.created_at between p_start and p_end and lower(coalesce(o.payment_status,'')) not in ('paid','success','successful','completed')),0),'visitors',(select count(distinct coalesce(nullif(e.session_id,''),e.actor_id::text,e.id::text)) from public.seller_events e where e.store_id=p_store_id and e.created_at between p_start and p_end),'views',(select count(*) from public.seller_events e where e.store_id=p_store_id and e.event_type in ('impression','view') and e.created_at between p_start and p_end),'engagement',(select count(*) from public.seller_events e where e.store_id=p_store_id and e.event_type='engagement' and e.created_at between p_start and p_end),'clicks',(select count(*) from public.seller_events e where e.store_id=p_store_id and e.event_type='product_click' and e.created_at between p_start and p_end),'carts',(select count(*) from public.seller_events e where e.store_id=p_store_id and e.event_type='cart' and e.created_at between p_start and p_end),'checkouts',(select count(*) from public.seller_events e where e.store_id=p_store_id and e.event_type='checkout' and e.created_at between p_start and p_end),'purchases',(select count(*) from public.orders o where o.store_id=p_store_id and o.created_at between p_start and p_end and lower(coalesce(o.payment_status,'')) in ('paid','success','successful','completed')),'customers',(select count(distinct o.buyer_id) from public.orders o where o.store_id=p_store_id and o.created_at between p_start and p_end and lower(coalesce(o.payment_status,'')) in ('paid','success','successful','completed')),'withdrawn',coalesce((select sum(p.amount) from public.seller_payouts p where p.store_id=p_store_id and lower(p.status) in ('paid','completed')),0),'transactions',coalesce((select jsonb_agg(jsonb_build_object('id',q.id,'amount',q.subtotal,'status',q.payment_status,'fulfillment_status',q.fulfillment_status,'created_at',q.created_at) order by q.created_at desc) from (select o.id,o.subtotal,o.payment_status,o.fulfillment_status,o.created_at from public.orders o where o.store_id=p_store_id order by o.created_at desc limit 25) q),'[]'::jsonb)) into result;
 return result;
end; $$;
grant execute on function public.get_seller_studio_metrics(uuid,timestamptz,timestamptz) to authenticated;